// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: proto/v1/k8scall.proto

/*
Package k8scall is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package k8scall

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_K8SCall_CreateObjectByJson_0(ctx context.Context, marshaler runtime.Marshaler, client K8SCallClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq K8SJson
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.CreateObjectByJson(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_K8SCall_CreateObjectByJson_0(ctx context.Context, marshaler runtime.Marshaler, server K8SCallServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq K8SJson
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.CreateObjectByJson(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterK8SCallHandlerServer registers the http handlers for service K8SCall to "mux".
// UnaryRPC     :call K8SCallServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterK8SCallHandlerFromEndpoint instead.
func RegisterK8SCallHandlerServer(ctx context.Context, mux *runtime.ServeMux, server K8SCallServer) error {

	mux.Handle("POST", pattern_K8SCall_CreateObjectByJson_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateIncomingContext(ctx, mux, req, "/api.K8SCall/CreateObjectByJson", runtime.WithHTTPPathPattern("/api.K8SCall/CreateObjectByJson"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_K8SCall_CreateObjectByJson_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_K8SCall_CreateObjectByJson_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterK8SCallHandlerFromEndpoint is same as RegisterK8SCallHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterK8SCallHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterK8SCallHandler(ctx, mux, conn)
}

// RegisterK8SCallHandler registers the http handlers for service K8SCall to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterK8SCallHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterK8SCallHandlerClient(ctx, mux, NewK8SCallClient(conn))
}

// RegisterK8SCallHandlerClient registers the http handlers for service K8SCall
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "K8SCallClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "K8SCallClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "K8SCallClient" to call the correct interceptors.
func RegisterK8SCallHandlerClient(ctx context.Context, mux *runtime.ServeMux, client K8SCallClient) error {

	mux.Handle("POST", pattern_K8SCall_CreateObjectByJson_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		var err error
		var annotatedContext context.Context
		annotatedContext, err = runtime.AnnotateContext(ctx, mux, req, "/api.K8SCall/CreateObjectByJson", runtime.WithHTTPPathPattern("/api.K8SCall/CreateObjectByJson"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_K8SCall_CreateObjectByJson_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_K8SCall_CreateObjectByJson_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_K8SCall_CreateObjectByJson_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"api.K8SCall", "CreateObjectByJson"}, ""))
)

var (
	forward_K8SCall_CreateObjectByJson_0 = runtime.ForwardResponseMessage
)
