// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.2
// source: proto/v1/modelserving.proto

package modelserving

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ModelServingClient is the client API for ModelServing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModelServingClient interface {
	ListApp(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAppResponse, error)
	GetAppParams(ctx context.Context, in *GetAppParamsRequest, opts ...grpc.CallOption) (*GetAppParamsResponse, error)
	GetAppCustomResource(ctx context.Context, in *GetRenderedCRRequest, opts ...grpc.CallOption) (*GetRenderedCRResponse, error)
}

type modelServingClient struct {
	cc grpc.ClientConnInterface
}

func NewModelServingClient(cc grpc.ClientConnInterface) ModelServingClient {
	return &modelServingClient{cc}
}

func (c *modelServingClient) ListApp(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetAppResponse, error) {
	out := new(GetAppResponse)
	err := c.cc.Invoke(ctx, "/api.ModelServing/ListApp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServingClient) GetAppParams(ctx context.Context, in *GetAppParamsRequest, opts ...grpc.CallOption) (*GetAppParamsResponse, error) {
	out := new(GetAppParamsResponse)
	err := c.cc.Invoke(ctx, "/api.ModelServing/GetAppParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelServingClient) GetAppCustomResource(ctx context.Context, in *GetRenderedCRRequest, opts ...grpc.CallOption) (*GetRenderedCRResponse, error) {
	out := new(GetRenderedCRResponse)
	err := c.cc.Invoke(ctx, "/api.ModelServing/GetAppCustomResource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelServingServer is the server API for ModelServing service.
// All implementations must embed UnimplementedModelServingServer
// for forward compatibility
type ModelServingServer interface {
	ListApp(context.Context, *emptypb.Empty) (*GetAppResponse, error)
	GetAppParams(context.Context, *GetAppParamsRequest) (*GetAppParamsResponse, error)
	GetAppCustomResource(context.Context, *GetRenderedCRRequest) (*GetRenderedCRResponse, error)
	mustEmbedUnimplementedModelServingServer()
}

// UnimplementedModelServingServer must be embedded to have forward compatible implementations.
type UnimplementedModelServingServer struct {
}

func (UnimplementedModelServingServer) ListApp(context.Context, *emptypb.Empty) (*GetAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListApp not implemented")
}
func (UnimplementedModelServingServer) GetAppParams(context.Context, *GetAppParamsRequest) (*GetAppParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppParams not implemented")
}
func (UnimplementedModelServingServer) GetAppCustomResource(context.Context, *GetRenderedCRRequest) (*GetRenderedCRResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppCustomResource not implemented")
}
func (UnimplementedModelServingServer) mustEmbedUnimplementedModelServingServer() {}

// UnsafeModelServingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelServingServer will
// result in compilation errors.
type UnsafeModelServingServer interface {
	mustEmbedUnimplementedModelServingServer()
}

func RegisterModelServingServer(s grpc.ServiceRegistrar, srv ModelServingServer) {
	s.RegisterService(&ModelServing_ServiceDesc, srv)
}

func _ModelServing_ListApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServingServer).ListApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ModelServing/ListApp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServingServer).ListApp(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelServing_GetAppParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServingServer).GetAppParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ModelServing/GetAppParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServingServer).GetAppParams(ctx, req.(*GetAppParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelServing_GetAppCustomResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRenderedCRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelServingServer).GetAppCustomResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ModelServing/GetAppCustomResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelServingServer).GetAppCustomResource(ctx, req.(*GetRenderedCRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModelServing_ServiceDesc is the grpc.ServiceDesc for ModelServing service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModelServing_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.ModelServing",
	HandlerType: (*ModelServingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListApp",
			Handler:    _ModelServing_ListApp_Handler,
		},
		{
			MethodName: "GetAppParams",
			Handler:    _ModelServing_GetAppParams_Handler,
		},
		{
			MethodName: "GetAppCustomResource",
			Handler:    _ModelServing_GetAppCustomResource_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/modelserving.proto",
}
