// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.2
// source: proto/v1/storage.proto

package storage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StorageClient is the client API for Storage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageClient interface {
	GetStorageTypes(ctx context.Context, in *GetStorageTypesRequest, opts ...grpc.CallOption) (*GetStorageTypesResponse, error)
	GetStorageParams(ctx context.Context, in *GetStorageParamsRequest, opts ...grpc.CallOption) (*GetStorageParamResponse, error)
	ListStorage(ctx context.Context, in *ListStorageRequest, opts ...grpc.CallOption) (*ListStorageResponse, error)
	GetRenderedStorageManifest(ctx context.Context, in *RenderedStorageRequest, opts ...grpc.CallOption) (*RenderedStorageResponse, error)
}

type storageClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageClient(cc grpc.ClientConnInterface) StorageClient {
	return &storageClient{cc}
}

func (c *storageClient) GetStorageTypes(ctx context.Context, in *GetStorageTypesRequest, opts ...grpc.CallOption) (*GetStorageTypesResponse, error) {
	out := new(GetStorageTypesResponse)
	err := c.cc.Invoke(ctx, "/api.Storage/GetStorageTypes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetStorageParams(ctx context.Context, in *GetStorageParamsRequest, opts ...grpc.CallOption) (*GetStorageParamResponse, error) {
	out := new(GetStorageParamResponse)
	err := c.cc.Invoke(ctx, "/api.Storage/GetStorageParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) ListStorage(ctx context.Context, in *ListStorageRequest, opts ...grpc.CallOption) (*ListStorageResponse, error) {
	out := new(ListStorageResponse)
	err := c.cc.Invoke(ctx, "/api.Storage/ListStorage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) GetRenderedStorageManifest(ctx context.Context, in *RenderedStorageRequest, opts ...grpc.CallOption) (*RenderedStorageResponse, error) {
	out := new(RenderedStorageResponse)
	err := c.cc.Invoke(ctx, "/api.Storage/GetRenderedStorageManifest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServer is the server API for Storage service.
// All implementations must embed UnimplementedStorageServer
// for forward compatibility
type StorageServer interface {
	GetStorageTypes(context.Context, *GetStorageTypesRequest) (*GetStorageTypesResponse, error)
	GetStorageParams(context.Context, *GetStorageParamsRequest) (*GetStorageParamResponse, error)
	ListStorage(context.Context, *ListStorageRequest) (*ListStorageResponse, error)
	GetRenderedStorageManifest(context.Context, *RenderedStorageRequest) (*RenderedStorageResponse, error)
	mustEmbedUnimplementedStorageServer()
}

// UnimplementedStorageServer must be embedded to have forward compatible implementations.
type UnimplementedStorageServer struct {
}

func (UnimplementedStorageServer) GetStorageTypes(context.Context, *GetStorageTypesRequest) (*GetStorageTypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStorageTypes not implemented")
}
func (UnimplementedStorageServer) GetStorageParams(context.Context, *GetStorageParamsRequest) (*GetStorageParamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStorageParams not implemented")
}
func (UnimplementedStorageServer) ListStorage(context.Context, *ListStorageRequest) (*ListStorageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStorage not implemented")
}
func (UnimplementedStorageServer) GetRenderedStorageManifest(context.Context, *RenderedStorageRequest) (*RenderedStorageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRenderedStorageManifest not implemented")
}
func (UnimplementedStorageServer) mustEmbedUnimplementedStorageServer() {}

// UnsafeStorageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageServer will
// result in compilation errors.
type UnsafeStorageServer interface {
	mustEmbedUnimplementedStorageServer()
}

func RegisterStorageServer(s grpc.ServiceRegistrar, srv StorageServer) {
	s.RegisterService(&Storage_ServiceDesc, srv)
}

func _Storage_GetStorageTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStorageTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).GetStorageTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Storage/GetStorageTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).GetStorageTypes(ctx, req.(*GetStorageTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_GetStorageParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStorageParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).GetStorageParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Storage/GetStorageParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).GetStorageParams(ctx, req.(*GetStorageParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_ListStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).ListStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Storage/ListStorage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).ListStorage(ctx, req.(*ListStorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_GetRenderedStorageManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderedStorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).GetRenderedStorageManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Storage/GetRenderedStorageManifest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).GetRenderedStorageManifest(ctx, req.(*RenderedStorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Storage_ServiceDesc is the grpc.ServiceDesc for Storage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Storage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Storage",
	HandlerType: (*StorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStorageTypes",
			Handler:    _Storage_GetStorageTypes_Handler,
		},
		{
			MethodName: "GetStorageParams",
			Handler:    _Storage_GetStorageParams_Handler,
		},
		{
			MethodName: "ListStorage",
			Handler:    _Storage_ListStorage_Handler,
		},
		{
			MethodName: "GetRenderedStorageManifest",
			Handler:    _Storage_GetRenderedStorageManifest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/storage.proto",
}
